Process events
click-contrib/sphinx-click pull request #126
Opened 2023-07-29 20:00 UTC by coloursofnoise

## Summary
Add Sphinx events to post-process generated command documentation.

## Tasks

- [x] Added unit tests
- [x] Added documentation for new features (where applicable)
- [x] Added release notes (using [`reno`](https://pypi.org/project/reno/))
- [x] Ran test suite and style checks and built documentation (`tox`)

## Further details

2023-07-31 10:59 UTC, stephenfin requested changes
Looks reasonable to me. Two small nits inline but otherwise I'm a-okay with this

2023-07-31 10:59 UTC, stephenfin commented on docs/usage.rst
> +
Could we get a small "hello, world"-like example of using this?

2023-07-31 10:59 UTC, stephenfin commented on sphinx_click/ext.py
> +    def decorator(func):
Can we add [`functools.wraps`](https://docs.python.org/3/library/functools.html#functools.wraps) to preserve the docstrings etc.? Also, type annotations?

2023-08-06 10:26 UTC, stephenfin commented
Just the style issues to fix now. You can do this by installing and running pre-commit.

```
pip install pre-commit
pre-commit run -a
```

That will automatically run `black` for you.

2023-08-08 19:53 UTC, coloursofnoise commented
Should be done, after a bit of confusion I realized that this branch doesn't have the latest changes to the `tox` and `pre-commit` config so I just ran `black` manually.

2023-08-09 09:45 UTC, merged

2023-08-17 12:57 UTC, caioariede commented
@stephenfin any plans on releasing this to PyPI? 👀